#!/bin/sh

#"additioner un chiffre"

chiffre1=0
chiffre2=0
reponse=0
echo "enttrer le chiffre1"
read chiffre1
echo "entrer le chiffre2"
read chiffre2
echo " voici a réponse"
echo $((chiffre1+chiffre2))
