#!/bin/bash
#date
Annee=`date +%Y`
Mois=`date +%m`
Jour=`date +%d`
if [[ $1 -gt 0 ]]
then
Annee=$1
elif [[ $2 -gt 0 ]]
then
Mois=$2
elif [[ $3 -gt 0 ]]
then
Jour=$3
else
echo ""
fi

mkdir $Annee 
mkdir $Annee/$Mois
echo "#!/bin/bash" >  $Annee/$Mois/$Jour.sh 
echo "#Fichier scipt" >> $Annee/$Mois/$Jour.sh
echo " " >>  $Annee/$Mois/$Jour.sh
echo " " >>  $Annee/$Mois/$Jour.sh
echo "#Fin de script" >>  $Annee/$Mois/$Jour.sh
chmod +x $Annee/$Mois/$Jour.sh
echo "Fini correctement"
