#!/bin/bash
declare codepostal
declare ville
declare nom
declare prenom
declare age
 
echo "où habite tu"
read ville
echo "quelle est ton code postal"
read codepostal
echo "quelle est ton nom"
read nom 
echo "quelle est ton prénom"
read prenom
echo "quelle âge a-tu"
read age 
echo "$ville $codepostal $nom $prenom $age"


