#!/bin/bash

declare chiffre1
declare chiffre2
declare operateur
declare quitter
until [[ $quitter -lt 0 ]]
do
echo "rentrer un chiffre"
read chiffre1
echo "rentrer un autre chiffre"
read chiffre2
echo "rentrer l'opérateur"
read operateur
echo $(($chiffre1$operateur$chiffre2))
echo "écriver q ou -1 pour quitter"
read quitter
if [ "$quitter" = "q" ]
then
quitter=-1
fi
done
