#!/bin/bash
#echo addition  
chiffre1=0 
chiffre2=0
operateur=0
quitter=0
until [[ $quitter -lt 0 ]]
do	
echo "Donner le chiffre 1"
read chiffre1

echo "ENTRER L OPERATEUR"
read operateur
echo "Donner le chiffre"
read chiffre2

echo "voici le reponse"
let "res=$chiffre1$operateur$chiffre2"
echo "Voici le résultat : $res"
echo "Voulez vous recomencer cliquer n'importe pour recommencer"
echo "ou sur q pour quitter"
read quitter
if [ "$quitter" = "q" ]
then
quitter=-1
else
echo ""
fi
done
