#!/bin/bash

declare chiffre
declare quitter 
declare resultat

until [[ $quitter -lt 0 ]]
do
echo "entrer votre chiffre"
read chiffre
let "resultat=$chiffre*$chiffre"
echo "voici le résultat:$resultat"
echo "pour quitter cliquer sur q ou -1"
read quitter 
if [ "$quitter" = "q" ]
then
quitter=-1
fi
done
