#!/bin/bash


res1="très bien" 
res2="bien" 
res3="bof" 
res4="Insuffisant" 
declare note
quitter=0







until [[ $quitter -lt 0 ]]
do
echo "Entrer votre note entre 0 et 20"
read note
if [[ $note -ge 18 ]]
then
echo "$res1"
elif [[ $note -ge 15 ]]
then
echo "$res2"
elif [[ $note -ge 12 ]]
then
echo "$res3"
else
echo "$res4"
fi
echo "Pour quitter cliquer sur q pour continuer cliquer n'importe ou"
read quitter
if [ "$quitter" = "q" ]
then
quitter=-1
else
echo ""
fi
done
