#!/bin/bash
#Martin
#Case test

echo "quel est le premier numéro ?"
read num1
echo "quel est le second numéro ?"
read num2
echo "tapez 1 pour une addition"
echo "tapez 2 pour une soustraction"
echo "tapez 3 pour une division"
echo "tapez 4 pour une multiplication"
read ope

case $ope in
"1")
echo "$(($num1+$num2))"
;;
"2")
echo "$(($num1-$num2))"
;;
"3")
echo "$(($num1/$num2))"
;;
"4")
echo "$(($num1*$num2))"
;;
*)
echo "je ne peux pas faire se calcul"
;;
esac
