#!/bin/bash
nanna=0
nmois=0
njour=0
nanna=$1
nmois=$2
njour=$3


if [[ $nanna -eq "0" ]] && [[ $nmois -eq "0" ]] && [[ $njour -eq "0" ]]
then
DATE=`date +%Y-%m-%d`
jour=`date +%d`
anne=`date +%Y`
mois=`date +%m`
mkdir $anne && mkdir $anne/$mois 
echo "#!/bin/bash" > $anne/$mois/$jour.sh
echo "#Martin Hoszowski" >> $anne/$mois/$jour.sh
fi
echo "$1$2$3"
mkdir $nanna 
mkdir $nanna/$nmois
echo "#!/bin/bash" > $nanne/$nmois/$njour.sh
echo "#Martin Hoszowski" >> $nanne/$nmois/$njour.sh

