#!/bin/bash
#Martin Notes
echo "quelle est ta note ?"
read var1
if [ $var1 -ge "18" ]
then
echo "Bravo !"
elif [ $var1 -eq "12" ]
then
echo "c'est acceptable mais tu peux faire mieux"
elif [ $var1 -eq "13" ]
then
echo "c'est une bonne note"
elif  [ $var1 -eq "14" ]
then
echo "c'est une bonne note"
elif [ $var1 -eq "15" ]
then
echo "c'est une bonne note"
elif [ $var1 -eq "16" ]
then
echo "c'est une bonne note"
elif [ $var1 -eq "17" ]
then
echo "c'est une bonne note"
elif [ $var1 -lt "12" ]
then 
echo "il faut réviser plus !"
fi
