#!/bin/bash
#Martin
#While
whi=0
whi2=0
while [ $whi -eq "0" ]
do
echo "Selectionez"
echo "1. Calculer l'addition d' un chffre"
echo "2.Donnez votre nom"
echo "3.Quittez"
read case
case $case in
"1")
echo "quel est le premier nombre ?"
read num1
echo "quel est le second nombre ?"
read num2
echo "$(($num1+$num2))"
;;
"2")
echo "quel est votre nom ?"
read nom1
echo "quel est votre prénom ?"
read nom2
echo "Bonjour $nom2 $nom1"
;;
"3")
echo "Au revoir"
whi=1
whi2=1
;;
esac
while [ $whi2 -eq "0" ]
do
echo "voulez vous recommencer ?"
read rep
case $rep in
"non")
whi=1
whi2=1
;;
"oui")
whi2=1
;;
*)
;;
esac
done
done
echo "Merci d'avoir participez et bonne journée"
