#!/bin/sh
##############################
#Crée par Poli################
#Licence GPLv3################
#Fichier : demandenomchiffre##
##############################
	reponse=0
	choix=0
	chiffre1=0
	chiffre2=0
	nom="0"
	prenom="0"
	while [[ $reponse -ne 1 ]]
	do
	echo "Selectionner"
        echo "1. Calcul de addition de chiffre"
        echo "2. Donner votre nom"
	echo "3. Quitter"
	read choix
	case $choix in
		1) while [[ chiffre1 -eq "0" ]]
			do
			echo "Choissisez le premier chiffre"
				read chiffre1
			done
		    while [[ $chiffre2 -eq "0" ]]
			do
	           	echo "Choissisez le deuxième chiffre"
				read chiffre2
			done
			echo "Sa donne :"
			echo $((chiffre1+chiffre2))
		    break	;;
		2) while [[ "$nom" = "0" ]]
			do 
		   	echo "Donnez moi votre nom"
				read nom
			done
		   while [[ "$prenom" = "0" ]]
			do
		   	echo "Donnez moi votre prénom"
				read prenom
			done
		    echo "Bonjour, $prenom $nom"
		    break	;;
		3) reponse=1
		    break	;;
		*) echo "Choisisez entre 1-3"
		   continue	;;
	esac
	if [ $reponse -ne "1" ]
                then
                echo "Voulez vous recommencer?"
                read $reponse
	else 
		echo "test"
        fi
done	
echo "Passez une bien bonne journée, au revoir"

