#!/bin/bash
#############################
#Crée par Poli###############
#Licence GPLv3###############
#Fichier : base##############
#############################
note=0

until [ "$note" -lt 0 ]
do
echo "Rentre q ou -1 pour quitter"
echo "Enter votre note"
read note
if [ "$note" -ge 16 ]
then
	echo "Très bien"
elif [ "$note" -ge 14 ]
then
	echo "Bien"
elif [ "$note" -ge 12 ]
then
	echo "Assez bien"
elif [ "$note" -ge 10 ]
then
	echo "Moyen"
elif [ "$note" = "q" ]
then 
	note=-1	
else
	echo "Insuffisant"
fi
done
echo "Au revoir" 
